services:
  postgresdb:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/data:db
    environment:
      - 'POSTGRES_USER=ticket_easy'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=ticket_easy'
    ports:
      - 5432:5432
volumes:
  postgres-data: