spring:
  application:
    name: ticket-easy
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_easy
    username: ticket_easy
    password: password

springdoc:
    api-docs:
      enabled: ${SWAGGER_ENABLE:true}

api:
  security:
    token:
      secret: ${JWT_SECRET:secret}}
  integrations:
      event:
        url: http://localhost:8081
        secret: secret